config/routes.rb
Rails.application.routes.draw do

  # Verifications
  post 'verifications/new'
  post 'verifications/confirm'

  # Users
  get  'users/check'
  post 'users/initialize_keys'
  post 'users/spot' => 'users#add_spot'
  post 'users/spots' => 'users#add_spots'

  # Session
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#logout'

  # Account
  get '/account(/:month-:day-:year)' => 'accounts#home', as: :account

  # Stream
  get '/stream' => 'home#stream', format: 'text'

  # Main Pages
  get '/done' => 'home#done', as: :done
  get '/privacy' => 'home#privacy', as: :privacy
  get '/tos' => 'home#tos', as: :tos
  
  # Demo?
  get 'demo' => 'demos#new', as: :demo
  post 'demo' => 'demos#create'

  root 'home#home'
  
end

app/models/demo.rb
# Represents a Demo Signup
#
# first_name:: 
# last_name:: 
# company:: 
# email::
# employees:: 
# interest:: 
class Demo < ActiveRecord::Base

  # Validations
  validates :first_name, :last_name, presence: true
  validates :company, presence: true
  validates :email, presence: true
  validates :employees, presence: true

  after_create { |demo| DemoMailer.new_demo(demo).deliver }
  
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to root_path, notice: t(:demo_complete) }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url, notice: 'Demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:first_name, :last_name, :company, :email, :employees, :interest)
    end
end

app/helpers/demos_helper.rb
module DemosHelper

  def employee_select_options
    {
      1 => "1 to 4",
      5 => "5 to 20",
      21 => "21 to 50",
      51 => "51 to 100",
      101 => "More than 100",
    }
  end

end

app/views/demos/_form.html.haml
= form_for @demo, :class => "form-horizontal", url: demo_path do |f|
  .form-header Access your Location Archive
  .form-body

    - if @demo.errors.any?
      #error_explanation
        - @demo.errors.full_messages.each do |msg|
          %span= msg

    .form-group.inset
      = f.label :first_name, "Phone #"
      = f.text_field :first_name, :class => "form-control"
    .form-group.inset
      = f.label :last_name, "Question 1"
      = f.text_field :last_name, :class => "form-control"
    .form-group.inset
      = f.label :email, "Question 2"
      = f.text_field :email, :class => "form-control"
    .form-group
      %button.btn.btn-primary.btn-block{type: 'submit'} Confirm Access

app/views/demos/edit.html.haml
%h1 Editing demo

= render 'form'

= link_to 'Show', @demo
\|
= link_to 'Back', demos_path

app/views/demos/index.html.haml
%h1 Listing demos

%table
  %tr
    %th First name
    %th Last name
    %th Company
    %th Email
    %th Employees
    %th Interest
    %th
    %th
    %th

  - @demos.each do |demo|
    %tr
      %td= demo.first_name
      %td= demo.last_name
      %td= demo.company
      %td= demo.email
      %td= demo.employees
      %td= demo.interest
      %td= link_to 'Show', demo
      %td= link_to 'Edit', edit_demo_path(demo)
      %td= link_to 'Destroy', demo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Demo', new_demo_path

app/views/demos/new.html.haml
%section#core
  .container
    .row
      .col-sm-5
        %h4 What exactly does BOSS Abilities do?
        %p We translate your company's data into profitable advice. We'll get to know you as a business owner, personally review your data (in whatever form it comes in), and help you grow your business.
        %h4 Will this take a lot of time?
        %p Gosh, no. Our goal is to save you time -- we'll do the heavy lifting of sorting, analyzing, and understanding your data, so you don't have to.
        %h4 How much does it cost?
        %p
          Our rate is completely negotiable, and is generally 1/10th of what you'd pay a standard consultant. We do this by using software to assist in our review and analysis process. And no matter what, we
          %i guarantee
          a positive ROI or your money back.
      .col-sm-6.col-sm-offset-1
        = render 'form'

app/views/demos/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @demo.first_name
%p
  %b Last name:
  = @demo.last_name
%p
  %b Company:
  = @demo.company
%p
  %b Email:
  = @demo.email
%p
  %b Employees:
  = @demo.employees
%p
  %b Interest:
  = @demo.interest

= link_to 'Edit', edit_demo_path(@demo)
\|
= link_to 'Back', demos_path